name: land_auction_app
description: A Flutter application for land auctions.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  http: ^1.1.0
  intl: ^0.18.1
  shared_preferences: ^2.2.0
  flutter_countdown_timer: ^4.1.0
  cached_network_image: ^3.2.3
  google_fonts: ^5.1.0
  supabase_flutter: ^2.9.1
  flutter_dotenv: ^5.1.0
  image_picker: ^1.0.4
  sign_in_with_apple: ^6.0.0
  url_launcher: ^6.0.9
  share_plus: ^11.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
